version: "3"

x-dev-base: &dev-base
  build: .
  environment:
    DB_HOST: mysql
    DB_PORT: 3306
    DB_USERNAME: docker
    DB_PASSWORD: docker
    DB_NAME: nest_next_sample
  volumes:
    - .:/app

services:

  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    command: mysqld
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: nest_next_sample
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf

  backend:
    << : *dev-base
    working_dir: /app/packages/backend
    command: yarn start:dev
    tty: true
    depends_on:
      - mysql
    ports:
      - "3000:3000"

#  chat-server:
#    <<: *dev-base
#    working_dir: /app/packages/chat/server
#    command: yarn start
#    tty: true
#    ports:
#      - "4000:4000"

#  chat-client:
#    <<: *dev-base
#    working_dir: /app/packages/chat/client
#    command: yarn start
#    tty: true
#    ports:
#      - "4001:4001"